import { Core } from "@blaze-cardano/sdk";
import { AssetAmount, IAssetAmountMetadata } from "@sundaeswap/asset";
import {
  EPoolCoin,
  TConditionDatumArgs,
  TDestination,
  TDestinationAddress,
  TOrderAddressesArgs,
  TUTXO,
} from "./datumbuilder.js";
import { ESwapType } from "./enums.js";
import { IPoolData } from "./queryprovider.js";

/**
 * The referral fee object if set.
 */
export interface ITxBuilderReferralFee {
  destination: string;
  payment: Core.Value;
  /** The label that prefixes the fee amount in the metadata. */
  feeLabel?: string;
}

/**
 * The base config that all configs extend.
 */
export interface IBaseConfig {
  referralFee?: ITxBuilderReferralFee;
}

/**
 * The common arguments for any valid order.
 */
export interface IOrderConfigArgs extends IBaseConfig {
  pool: IPoolData;
  orderAddresses: TOrderAddressesArgs;
  ownerAddress?: string;
}

/**
 * An interface that represents a market order
 * swap with required slippage.
 */
export interface IMarketSwap {
  type: ESwapType.MARKET;
  slippage: number;
}

/**
 * An interface that represents a limit order
 * swap with required minimum receivable.
 */
export interface ILimitSwap {
  type: ESwapType.LIMIT;
  minReceivable: AssetAmount<IAssetAmountMetadata>;
}

/**
 * A union type to represent all possible swap types.
 */
export type TSwapType = IMarketSwap | ILimitSwap;

/**
 * The arguments configuration for building a valid Swap.
 */
export interface ISwapConfigArgs extends IOrderConfigArgs {
  suppliedAsset: AssetAmount<IAssetAmountMetadata>;
  swapType: TSwapType;
}

/**
 * The arguments configuration for building a valid Deposit.
 */
export interface IDepositConfigArgs extends IOrderConfigArgs {
  suppliedAssets: [
    AssetAmount<IAssetAmountMetadata>,
    AssetAmount<IAssetAmountMetadata>,
  ];
}

/**
 * The arguments configuration for building a valid cancellation transaction.
 */
export interface ICancelConfigArgs extends IBaseConfig {
  ownerAddress?: string;
  utxo: TUTXO;
}

/**
 * The arguments configuration for building a valid Deposit.
 */
export interface IZapConfigArgs extends IOrderConfigArgs {
  suppliedAsset: AssetAmount<IAssetAmountMetadata>;
  zapDirection: EPoolCoin;
  swapSlippage?: number;
}

/**
 * The arguments configuration for building a valid Withdraw.
 */
export interface IWithdrawConfigArgs extends Omit<IOrderConfigArgs, "pool"> {
  suppliedLPAsset: AssetAmount<IAssetAmountMetadata>;
}

/**
 * The arguments configuration for building a valid Strategy.
 */
export interface IStrategyConfigArgs
  extends Omit<IOrderConfigArgs, "orderAddresses"> {
  suppliedAsset: AssetAmount<IAssetAmountMetadata>;
  destination: TDestination;
  ownerAddress: string;
  authSigner?: string;
  authScript?: string;
}

export interface IStrategyConfigInputArgs
  extends Omit<IStrategyConfigArgs, "ownerAddress"> {
  ownerAddress?: string;
}

export interface IFeesConfig {
  ask: bigint;
  bid: bigint;
}

/**
 * Interface describing the method arguments for creating a pool
 * in the V3 Pool Contract.
 */
export interface IMintPoolConfigArgs extends IBaseConfig {
  assetA: AssetAmount<IAssetAmountMetadata>;
  assetB: AssetAmount<IAssetAmountMetadata>;
  fees: bigint | IFeesConfig;
  ownerAddress: string;
  // Defaults to immediately.
  marketOpen?: bigint;
  /**
   * This will send a percentage of LP tokens generated by creating the pool
   * to the SundaeSwap Treasury wallet.
   */
  donateToTreasury?: bigint;
  /**
   * The fee manager address for the pool. If not provided, defaults to null.
   */
  feeManager?: string;
  condition?: string;
  conditionDatumArgs?: TConditionDatumArgs;
}

/**
 * Interface describing migrations for liquidity
 * positions in a user's wallet.
 */
export interface IMigrateLiquidityConfig {
  withdrawConfig: IWithdrawConfigArgs & { pool: IPoolData };
  depositPool: IPoolData;
  newLockedAssets?: Record<string, IAssetAmountMetadata & { amount: bigint }>;
}

/**
 * Interface describing migrations for locked liquidity
 * positions in the Yield Farming contract.
 */
export interface IMigrateYieldFarmingLiquidityConfig {
  ownerAddress: TDestinationAddress;
  existingPositions?: TUTXO[];
  migrations: {
    withdrawPool: IPoolData;
    depositPool: IPoolData;
  }[];
}

/**
 * Type interface to describe the Strategy config type.
 */
export type TUpdateStrategy = {
  type: "Strategy";
  args: IStrategyConfigArgs;
};

/**
 * Type interface to describe the Swap config type.
 */
export type TUpdateSwap = {
  type: "Swap";
  args: ISwapConfigArgs;
};

/**
 * Union to bind together the different config types.
 */
export type TUpdateConfig = TUpdateSwap | TUpdateStrategy;

/**
 * Interface for updating an order with a set of considered
 * configuration types.
 */
export interface IUpdateArgs {
  cancelConfig: ICancelConfigArgs;
  updateConfig: TUpdateConfig;
}
